# Generated by Django 5.1.7 on 2025-04-20 19:03

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3791704a-84f7-4df0-9faf-d3435c70f2d4'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Draft'), ('R', 'Deleted'), ('C', 'Closed')], max_length=7)),
                ('winners', models.IntegerField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime(2025, 4, 21, 19, 3, 33, 992879))),
                ('voting_creator', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='votings.voting')),
            ],
        ),
    ]
