# Generated by Django 5.1.7 on 2025-04-20 19:03

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 19, 3, 48, 880640)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='id',
            field=models.UUIDField(default=uuid.UUID('faf77290-3ea4-46ed-ab7a-055049231b4c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
