# Generated by Django 5.1.7 on 2025-04-20 19:03

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0002_alter_voting_end_date_alter_voting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 19, 3, 58, 521581)),
        ),
        migrations.AlterField(
            model_name='voting',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e011c9dd-1869-40f7-a245-dca26db7c30f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
