# Generated by Django 5.1.7 on 2025-04-24 11:15

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("votings", "0007_alter_voting_end_date_alter_voting_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voting",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 25, 11, 15, 10, 252868)
            ),
        ),
        migrations.AlterField(
            model_name="voting",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="voting",
            name="voting_creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.admin"
            ),
        ),
    ]
