# Generated by Django 5.1.7 on 2025-04-20 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('votings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.JSONField(verbose_name='options')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votings.voting')),
            ],
        ),
    ]
